package services

import "testing"

// TestIsGeneratedFile covers the cross-language generated-file detection: every
// ecosystem dupehound supports stamps its output differently, so both the
// filename-suffix and content-marker paths are exercised here, alongside
// hand-written files that must NOT be flagged.
func TestIsGeneratedFile(t *testing.T) {
	cases := []struct {
		name    string
		path    string
		content string
		want    bool
	}{
		// --- filename-suffix detection, spanning languages ---
		{"go protobuf", "api/types.pb.go", "package api\n", true},
		{"go stringer", "color_string.go", "package x\n", true},
		{"python protobuf", "svc/types_pb2.py", "x = 1\n", true},
		{"cpp protobuf header", "msg.pb.h", "#pragma once\n", true},
		{"ts graphql-codegen", "queries.generated.ts", "export const x = 1\n", true},
		{"csharp designer", "Form1.Designer.cs", "namespace App {}\n", true},
		{"dart freezed", "user.freezed.dart", "part of 'user.dart';\n", true},

		// --- content-marker detection, language-agnostic ---
		{"go marker", "x.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n", true},
		{"ts relay marker", "x.ts", "/**\n * @generated SignedSource<<abc>>\n */\nexport {}\n", true},
		{"csharp marker", "X.cs", "// <auto-generated>\n//   This code was generated.\n// </auto-generated>\n", true},
		{"dart marker", "x.dart", "// GENERATED CODE - DO NOT MODIFY BY HAND\n", true},
		{"java marker", "X.java", "// This file was automatically generated.\nclass X {}\n", true},
		{"python marker", "x.py", "# Generated by the protocol buffer compiler. DO NOT EDIT!\n", true},

		// --- hand-written files must not be flagged ---
		{"plain go", "main.go", "package main\nfunc main() {}\n", false},
		{"plain ts", "app.ts", "export function add(a: number, b: number) { return a + b }\n", false},
		{"comment mentioning edit", "x.go", "// Please do not edit this without review? no — written normally.\n", false},
		{"unrelated header", "x.py", "# A normal module that was written by a human, generated nothing.\n", false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := isGeneratedFile(tc.path, tc.content); got != tc.want {
				t.Errorf("isGeneratedFile(%q) = %v, want %v", tc.path, got, tc.want)
			}
		})
	}
}
